// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjcuixpzwdlxyjixexay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqY3VpeHB6d2RseHlqaXhleGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mzc0NjcsImV4cCI6MjA3MDUxMzQ2N30.IFWhj7W_X9eye2NaSM25-fzghFi0nkBNDoaK_UiF5ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});